## 실제 사용 가능한 시계열성 외생변수 추출

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#GenAge = pd.read_csv('Covid19GenAgeCaseInf.csv')
InfState = pd.read_csv('Covid19InfState.csv')
#NatInfState = pd.read_csv('Covid19NatInfState.csv', encoding = 'utf-8')
#SidoInfState = pd.read_csv('Covid19SidoInfState.csv')

In [ ]:
#GenAge.tail(30)

In [ ]:
InfState.head(50)

,seq,stateDt,stateTime,decideCnt,clearCnt,examCnt,deathCnt,careCnt,resutlNegCnt,accExamCnt,accExamCompCnt,accDefRate,createDt,updateDt
0,1231,20230420,00:00,31039863.0,NaN,NaN,34401.0,NaN,NaN,NaN,NaN,NaN,2023-04-20 04:28:58.0,2023-04-20 04:30:13.0
1,1230,20230419,00:00,31025769.0,NaN,NaN,34392.0,NaN,NaN,NaN,NaN,NaN,2023-04-19 00:22:49.0,NaN
2,1229,20230418,00:00,31009261.0,NaN,NaN,34386.0,NaN,NaN,NaN,NaN,NaN,2023-04-18 00:38:03.0,NaN
3,1228,20230417,00:00,30994088.0,NaN,NaN,34376.0,NaN,NaN,NaN,NaN,NaN,2023-04-17 02:38:13.0,2023-04-17 08:38:15.0
4,1226,20230415,00:00,30978954.0,NaN,NaN,34368.0,NaN,NaN,NaN,NaN,NaN,2023-04-15 00:09:15.0,NaN
5,1225,20230414,00:00,30967692.0,NaN,NaN,34366.0,NaN,NaN,NaN,NaN,NaN,2023-04-14 00:07:08.0,NaN
6,1224,20230413,00:00,30956026.0,NaN,NaN,34361.0,NaN,NaN,NaN,NaN,NaN,2023-04-13 06:17:09.0,NaN
7,1223,20230412,00:00,30944430.0,NaN,NaN,34356.0,NaN,NaN,NaN,NaN,NaN,2023-04-12 03:42:57.0,NaN
8,1222,20230411,00:00,30930504.0,NaN,NaN,34342.0,NaN,NaN,NaN,NaN,NaN,2023-04-11 00:11:59.0,NaN
9,1221,20230410,00:00,30918060.0,NaN,NaN,34332.0,NaN,NaN,NaN,NaN,NaN,2023-04-10 00:16:15.0,2023-04-10 08:31:39.0
10,1219,20230408,00:00,30904502.0,NaN,NaN,34322.0,NaN,NaN,NaN,NaN,NaN,2023-04-08 03:05:05.0,NaN
11,1218,20230407,00:00,30894559.0,NaN,NaN,34318.0,NaN,NaN,NaN,NaN,NaN,2023-04-07 00:16:52.0,NaN
12,1216,20230405,00:00,30871740.0,NaN,NaN,34296.0,NaN,NaN,NaN,NaN,NaN,2023-04-05 02:12:00.0,NaN
13,1215,20230404,00:00,30857275.0,NaN,NaN,34289.0,NaN,NaN,NaN,NaN,NaN,2023-04-04 05:10:20.0,NaN
14,1214,20230403,00:00,30843900.0,NaN,NaN,34281.0,NaN,NaN,NaN,NaN,NaN,2023-04-03 00:00:13.0,2023-04-03 04:18:40.0
15,1212,20230401,00:00,30829827.0,NaN,NaN,34270.0,NaN,NaN,NaN,NaN,NaN,2023-04-01 00:03:42.0,NaN
16,1211,20230331,00:00,30820130.0,NaN,NaN,34265.0,NaN,NaN,NaN,NaN,NaN,2023-03-31 02:03:57.0,NaN
17,1210,20230330,00:00,30809762.0,NaN,NaN,34255.0,NaN,NaN,NaN,NaN,NaN,2023-03-30 00:35:56.0,NaN
18,1209,20230329,00:00,30798723.0,NaN,NaN,34245.0,NaN,NaN,NaN,NaN,NaN,2023-03-29 00:43:53.0,NaN
19,1208,20230328,00:00,30785589.0,NaN,NaN,34231.0,NaN,NaN,NaN,NaN,NaN,2023-03-28 02:58:50.0,NaN
20,1207,20230327,00:00,30773460.0,NaN,NaN,34223.0,NaN,NaN,NaN,NaN,NaN,2023-03-27 00:01:50.0,NaN
21,1205,20230325,00:00,30759895.0,NaN,NaN,34217.0,NaN,NaN,NaN,NaN,NaN,2023-03-25 00:22:01.0,NaN
22,1204,20230324,00:00,30749740.0,NaN,NaN,34211.0,NaN,NaN,NaN,NaN,NaN,2023-03-24 05:46:03.0,NaN
23,1203,20230323,00:00,30739457.0,NaN,NaN,34201.0,NaN,NaN,NaN,NaN,NaN,2023-03-23 01:46:31.0,NaN
24,1202,20230322,00:00,30728057.0,NaN,NaN,34187.0,NaN,NaN,NaN,NaN,NaN,2023-03-22 00:01:22.0,NaN
25,1201,20230321,00:00,30714976.0,NaN,NaN,34178.0,NaN,NaN,NaN,NaN,NaN,2023-03-21 00:47:09.0,NaN
26,1200,20230320,00:00,30702960.0,NaN,NaN,34171.0,NaN,NaN,NaN,NaN,NaN,2023-03-20 02:11:21.0,2023-03-20 02:36:53.0
27,1198,20230318,00:00,30690223.0,NaN,NaN,34159.0,NaN,NaN,NaN,NaN,NaN,2023-03-18 00:03:26.0,NaN
28,1197,20230317,00:00,30681228.0,NaN,NaN,34155.0,NaN,NaN,NaN,NaN,NaN,2023-03-17 02:04:30.0,NaN
29,1195,20230315,00:00,30662229.0,NaN,NaN,34131.0,NaN,NaN,NaN,NaN,NaN,2023-03-15 05:29:17.0,NaN
30,1194,20230314,00:00,30650330.0,NaN,NaN,34121.0,NaN,NaN,NaN,NaN,NaN,2023-03-14 00:01:36.0,NaN
31,1193,20230313,00:00,30638929.0,NaN,NaN,34115.0,NaN,NaN,NaN,NaN,NaN,2023-03-13 00:40:54.0,2023-03-13 09:53:44.0
32,1189,20230311,00:00,30625389.0,NaN,NaN,34096.0,NaN,NaN,NaN,NaN,NaN,2023-03-11 04:28:57.0,NaN
33,1188,20230310,00:00,30615522.0,NaN,NaN,34093.0,NaN,NaN,NaN,NaN,NaN,2023-03-10 00:35:45.0,NaN
34,1187,20230309,00:00,30605187.0,NaN,NaN,34081.0,NaN,NaN,NaN,NaN,NaN,2023-03-09 00:05:14.0,NaN
35,1186,20230308,00:00,30594297.0,NaN,NaN,34061.0,NaN,NaN,NaN,NaN,NaN,2023-03-08 02:46:21.0,NaN
36,1184,20230306,00:00,30569215.0,NaN,NaN,34034.0,NaN,NaN,NaN,NaN,NaN,2023-03-06 00:05:25.0,NaN
37,1182,20230304,00:00,30555102.0,NaN,NaN,34020.0,NaN,NaN,NaN,NaN,NaN,2023-03-04 11:07:22.0,NaN
38,1180,20230303,00:00,30543981.0,NaN,NaN,34014.0,NaN,NaN,NaN,NaN,NaN,2023-03-03 04:01:40.0,NaN
39,1179,20230302,00:00,30533573.0,NaN,NaN,34003.0,NaN,NaN,NaN,NaN,NaN,2023-03-02 00:15:34.0,NaN
40,1178,20230301,00:00,30526012.0,NaN,NaN,33988.0,NaN,NaN,NaN,NaN,NaN,2023-03-01 00:14:58.0,NaN
41,1177,20230228,00:00,30513721.0,NaN,NaN,33977.0,NaN,NaN,NaN,NaN,NaN,2023-02-28 03:00:44.0,NaN
42,1176,20230227,00:00,30502904.0,NaN,NaN,33961.0,NaN,NaN,NaN,NaN,NaN,2023-02-27 03:08:07.0,2023-02-27 15:21:18.0
43,1174,20230225,00:00,30489666.0,NaN,NaN,33940.0,NaN,NaN,NaN,NaN,NaN,2023-02-25 00:02:32.0,NaN
44,1172,20230223,00:00,30469702.0,NaN,NaN,33909.0,NaN,NaN,NaN,NaN,NaN,2023-02-23 03:47:45.0,NaN
45,1170,20230221,00:00,30445775.0,NaN,NaN,33873.0,NaN,NaN,NaN,NaN,NaN,2023-02-21 00:03:30.0,NaN
46,1168,20230219,00:00,30429571.0,NaN,NaN,33856.0,NaN,NaN,NaN,NaN,NaN,2023-02-19 05:22:17.0,NaN
47,1166,20230217,00:00,30408656.0,NaN,NaN,33832.0,NaN,NaN,NaN,NaN,NaN,2023-02-17 00:10:01.0,NaN
48,1164,20230215,00:00,30384701.0,NaN,NaN,33782.0,NaN,NaN,NaN,NaN,NaN,2023-02-15 05:58:32.0,NaN
49,1163,20230214,00:00,30369744.0,NaN,NaN,33758.0,NaN,NaN,NaN,NaN,NaN,2023-02-14 00:21:47.0,NaN

In [ ]:
#NatInfState.head(50)

In [ ]:
#SidoInfState.head(50)

In [ ]:
df1 = InfState[['stateDt',	'decideCnt',	'clearCnt',	'examCnt',	'deathCnt', 'careCnt',	'resutlNegCnt',	'accExamCnt',	'accExamCompCnt',	'accDefRate']]
df1.head()

,stateDt,decideCnt,clearCnt,examCnt,deathCnt,careCnt,resutlNegCnt,accExamCnt,accExamCompCnt,accDefRate
0,20230420,31039863.0,NaN,NaN,34401.0,NaN,NaN,NaN,NaN,NaN
1,20230419,31025769.0,NaN,NaN,34392.0,NaN,NaN,NaN,NaN,NaN
2,20230418,31009261.0,NaN,NaN,34386.0,NaN,NaN,NaN,NaN,NaN
3,20230417,30994088.0,NaN,NaN,34376.0,NaN,NaN,NaN,NaN,NaN
4,20230415,30978954.0,NaN,NaN,34368.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
InfState.tail(20)

,seq,stateDt,stateTime,decideCnt,clearCnt,examCnt,deathCnt,careCnt,resutlNegCnt,accExamCnt,accExamCompCnt,accDefRate,createDt,updateDt
1128,20,20200211,16:00,28.0,4.0,762.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-11 17:09:25.25,NaN
1129,19,20200211,09:00,28.0,4.0,865.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-11 9:50:10.10,NaN
1130,18,20200210,16:00,27.0,3.0,531.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-10 17:03:49.49,2020-02-10 19:04:27.27
1131,17,20200210,09:00,27.0,3.0,809.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-10 9:56:41.41,NaN
1132,16,20200209,16:00,27.0,3.0,888.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-09 16:59:21.21,NaN
1133,15,20200209,09:00,25.0,3.0,960.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-09 9:58:22.22,2020-02-09 11:08:56.56
1134,14,20200208,16:00,24.0,2.0,939.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-08 17:01:34.34,NaN
1135,13,20200208,16:00,24.0,2.0,939.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-08 17:01:12.12,NaN
1136,12,20200208,16:00,24.0,2.0,939.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-08 16:48:05.05,NaN
1137,11,20200208,16:00,24.0,2.0,939.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-08 16:00:22.22,NaN
1138,10,20200208,09:00,24.0,2.0,620.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-08 10:09:34.34,NaN
1139,9,20200207,16:00,24.0,2.0,327.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-07 17:20:45.45,NaN
1140,8,20200207,09:00,24.0,2.0,264.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-07 9:53:27.27,2020-02-07 11:44:30.30
1141,7,20200206,09:00,23.0,1.0,169.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-06 9:09:49.49,2020-02-06 10:04:35.35
1142,6,20200205,19:00,19.0,1.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-05 20:05:40.40,2020-02-06 10:05:36.36
1143,5,20200205,09:00,18.0,NaN,129.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-04 23:56:31.31,2020-02-05 9:43:16.16
1144,4,20200204,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-03 21:26:59.59,NaN
1145,3,20200203,09:00,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-03 14:41:17.17,2020-02-04 14:19:46.46
1146,2,20200202,09:00,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2020-02-03 12:22:49.49,NaN
1147,1,20200101,18:00,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-31 17:47:33.33,2020-02-03 12:21:56.56

In [ ]:
InfState.isnull().sum()

seq                  0
stateDt              0
stateTime            0
decideCnt            2
clearCnt           458
examCnt            457
deathCnt            37
careCnt            515
resutlNegCnt       515
accExamCnt         457
accExamCompCnt     515
accDefRate         515
createDt             0
updateDt          1063
dtype: int64

In [ ]:
InfState.drop(['createDt', 'updateDt', 'seq'], axis = 1, inplace = True)

In [ ]:
InfState

,stateDt,stateTime,decideCnt,clearCnt,examCnt,deathCnt,careCnt,resutlNegCnt,accExamCnt,accExamCompCnt,accDefRate
0,20230420,00:00,31039863.0,NaN,NaN,34401.0,NaN,NaN,NaN,NaN,NaN
1,20230419,00:00,31025769.0,NaN,NaN,34392.0,NaN,NaN,NaN,NaN,NaN
2,20230418,00:00,31009261.0,NaN,NaN,34386.0,NaN,NaN,NaN,NaN,NaN
3,20230417,00:00,30994088.0,NaN,NaN,34376.0,NaN,NaN,NaN,NaN,NaN
4,20230415,00:00,30978954.0,NaN,NaN,34368.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1143,20200205,09:00,18.0,NaN,129.0,NaN,NaN,NaN,NaN,NaN,NaN
1144,20200204,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1145,20200203,09:00,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1146,20200202,09:00,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
1147,20200101,18:00,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
InfState = InfState.groupby('stateDt').first().reset_index()

In [ ]:
InfState = InfState.sort_values('stateDt', ascending = False).reset_index(drop = True)

In [ ]:
InfState

,stateDt,stateTime,decideCnt,clearCnt,examCnt,deathCnt,careCnt,resutlNegCnt,accExamCnt,accExamCompCnt,accDefRate
0,20230420,00:00,31039863.0,NaN,NaN,34401.0,NaN,NaN,NaN,NaN,NaN
1,20230419,00:00,31025769.0,NaN,NaN,34392.0,NaN,NaN,NaN,NaN,NaN
2,20230418,00:00,31009261.0,NaN,NaN,34386.0,NaN,NaN,NaN,NaN,NaN
3,20230417,00:00,30994088.0,NaN,NaN,34376.0,NaN,NaN,NaN,NaN,NaN
4,20230415,00:00,30978954.0,NaN,NaN,34368.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1106,20200205,19:00,19.0,1.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN
1107,20200204,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1108,20200203,09:00,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1109,20200202,09:00,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
1110,20200101,18:00,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
InfState.isnull().sum()

stateDt             0
stateTime           0
decideCnt           2
clearCnt          457
examCnt           457
deathCnt           18
careCnt           485
resutlNegCnt      485
accExamCnt        427
accExamCompCnt    485
accDefRate        485
dtype: int64

In [ ]:
InfState.drop('stateTime', axis = 1, inplace = True)

In [ ]:
InfState

,stateDt,decideCnt,clearCnt,examCnt,deathCnt,careCnt,resutlNegCnt,accExamCnt,accExamCompCnt,accDefRate
0,20230420,31039863.0,NaN,NaN,34401.0,NaN,NaN,NaN,NaN,NaN
1,20230419,31025769.0,NaN,NaN,34392.0,NaN,NaN,NaN,NaN,NaN
2,20230418,31009261.0,NaN,NaN,34386.0,NaN,NaN,NaN,NaN,NaN
3,20230417,30994088.0,NaN,NaN,34376.0,NaN,NaN,NaN,NaN,NaN
4,20230415,30978954.0,NaN,NaN,34368.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1106,20200205,19.0,1.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN
1107,20200204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1108,20200203,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1109,20200202,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
1110,20200101,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN